### ISSUE TITLE
Pubmed parser does not support DOCTYPE line in Pubmed Article XML

### ISSUE THREAD

**Issue by cloudronin** [thecloudcircle/pubmed-parser#2]
Pubmed Articles usually have the DOCTYPE line defined like so:

<!DOCTYPE PubmedArticleSet SYSTEM "http://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_190101.dtd">

This seems to break the Pubmed parser currently. Attached example pubmed xml file that will repro the issue.
Replace the pubmed.xml in the /pubmed folder with the attached file (after extracting it from the zip archive) and try running the build again to see the error

The following error is throw on build (while running the Sample test class)

    [java] Exception in thread "main" jakarta.xml.bind.UnmarshalException
     [java]  - with linked exception:
     [java] [org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 94; External DTD: Failed to read external DTD 'pubmed_190101.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.]
     [java] 	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:310)
     [java] 	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:538)
     [java] 	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:224)
     [java] 	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:189)
     [java] 	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
     [java] 	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:179)
     [java] 	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:164)
     [java] 	at DTDSample.test(DTDSample.java:44)
     [java] 	at DTDSample.main(DTDSample.java:30)
     [java] Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 94; External DTD: Failed to read external DTD 'pubmed_190101.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1148)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
     [java] 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
     [java] 	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:218)
     [java] 	... 6 more
     [java] Java Result: 1

[pubmed.xml.zip](https://github.com/thecloudcircle/pubmed-parser/files/6370929/pubmed.xml.zip)

**Comment by cloudronin** [comment]
Closing issue for now
